version: '3.8'
services:
  whisper:
    image: ruzil357/whisperx:v1.0.0
    ports:
      - "5000:5000"
    environment:
      - COMPUTE_TYPE=int8
  web:
    build: .
    command: uvicorn webapp.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - output_volume:/app/output
    ports:
      - "8000:8000"
    environment:
      - WHISPER_SERVICE_URL=http://whisper:5000
      - WEB_SERVICE_URL=http://web:8000
    depends_on:
      - whisper
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - output_volume:/output
    depends_on:
      - web
  volumes:
    output_volume: {}
