# Generated by Django 5.0.2 on 2024-02-18 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sid", models.CharField(max_length=100)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("company_name", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("feedback", models.TextField(null=True)),
                ("transcript", models.TextField(null=True)),
                ("confidence", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "uid")},
            },
        ),
    ]
